steps:
- name: 'bash'
  # env:
  # - 'GPG_PASSPHRASE=$_G_PASSPHRASE'
  script: 'echo "$$GPG_PASSPHRASE" | sudo gpg --batch --passphrase-fd 0 --output ./src/main/resources/application-security.yml --decrypt ./src/main/resources/application-security.yml.gpg'
#  args: ['echo', '$GPG_PASSPHRASE', '|', 'sudo', 'gpg', '--batch', '--passphrase-fd', '0', '--output', './src/main/resources/application-security.yml', '--decrypt', './src/main/resources/application-security.yml.gpg']
  secretEnv: ['GPG_PASSPHRASE']
  availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/${_GPG_SECRETS_NAME}/versions/1
    env: 'GPG_PASSPHRASE'
- name: maven:3-jdk-17
  entrypoint: mvn
  args: ['clean', 'package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cafelog-java', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['compose', '-f', 'docker-compose.yml', 'up']