version: '3.6'
services:
  app:
    container_name: cafelog-java
    image: takku66/cafelog
    ports:
      - 8888:8080
    depends_on:
      - db
  db:
    container_name: cafelog-postgres
    image: postgres:14.0
    volumes:
      - ./docker/pg/data:/var/lib/postgresql/data
      - ./docker/pg/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafelog
    ports:
      - 5433:5432
  
  
