version: '3.6'
services:
  web:
    container_name: cafelog-java
    image: takku66/cafelog
    ports:
      - 8888:8080
    depends_on:
      - db
    restart: always
  db:
    container_name: cafelog-postgres
    image: postgres:14.0
    volumes:
      - ./docker/pg/data:/var/lib/postgresql/data
      - ./docker/pg/scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafelog
    ports:
      - 5433:5432
    restart: always
  https-portal:
    image: steveltn/https-portal:1
    ports:
            - 80:80
            - 443:443
    links:
            - web
    restart: always
    environment:
      # DOMAINS: '35.197.22.32 -> http://web:8080'
      DOMAINS: 'localhost -> http://web:8080'
      STAGE: 'production' # Don't use production until staging works
      #FORCE_RENEW: 'true'
    container_name: https-portal
    volumes:
            - ./ssl_certs:/var/lib/https-portal
volumes:
    ssl_certs:
  
