spring:
  profiles:
    active: 
      - security
      - local
  datasource:
    url: jdbc:postgresql://localhost:5433/cafelog
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      springframework: WARN
    com:
      cafelog:
        mapper: 
          FavoritesMapper: DEBUG
          CafeLogUserMapper: DEBUG