@startuml Cafe Log UserCase

actor ユーザー
left to right direction
rectangle カフェ・喫茶店 {
    
    ユーザー -- (カフェ・喫茶店の本を見る)
    ユーザー -- (カフェ・喫茶店までの所要時間を検索する)
    ユーザー -- (カフェ・喫茶店までの道を検索する)
    ユーザー -- (カフェ・喫茶店に行く)
    ユーザー -- (カフェ・喫茶店の感想を書く)
}

@enduml